version: "3.8"

services:
  backend:
    build: ./backend
    ports:
      - "3050:3050"
    volumes:
      - ./backend:/servera
    environment:
      - FLASK_ENV=production
    restart: always


  frontend:
    build: ./TrueHue
    ports:
      - "19000:19000"
      - "19001:19001"
      - "19002:19002"
    volumes:
      - ./TrueHue:/app
      - /app/node_modules
    depends_on:
      - backend
    environment:
      - REACT_NATIVE_PACKAGER_HOSTNAME=0.0.0.0
      - EXPO_DEVTOOLS_LISTEN_ADDRESS=0.0.0.0
      - EXPO_PUBLIC_API_URL=http://backend:3050
    restart: always
